# Generated by Django 2.1.7 on 2019-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='chemical_formula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='chemical_formula',
            field=models.CharField(max_length=100),
        ),
    ]
