# Generated by Django 2.1.7 on 2019-05-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0003_auto_20190426_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='pld_batch_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
