# Generated by Django 2.1.7 on 2019-05-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0004_batch_pld_batch_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['id', 'batch__id', 'substrate']},
        ),
        migrations.AddField(
            model_name='target',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='furnace_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='samplelist.FurnaceSequence'),
        ),
    ]
