# Generated by Django 2.1.7 on 2019-05-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0005_auto_20190510_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='is_commercial',
        ),
        migrations.AddField(
            model_name='furnacesequence',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='furnacesequence',
            name='furnace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samplelist.Furnace'),
        ),
    ]
