# Generated by Django 2.1.7 on 2019-05-12 07:33

from django.db import migrations, models
import samplelist.models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0006_auto_20190510_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnacesequence',
            name='is_commercial',
        ),
        migrations.AddField(
            model_name='target',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mtcurve',
            name='data_file',
            field=models.FileField(upload_to=samplelist.models.mh_file_name),
        ),
    ]
