# Generated by Django 2.1.7 on 2019-05-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0007_auto_20190512_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPMSDataTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('magnetic_field', models.FloatField()),
                ('temperature', models.FloatField()),
                ('long_moment', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mhcurve',
            name='raw_file',
        ),
        migrations.RemoveField(
            model_name='mhcurve',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='mtcurve',
            name='raw_file',
        ),
        migrations.RemoveField(
            model_name='mtcurve',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='mpmsrawfile',
            name='user',
        ),
        migrations.AddField(
            model_name='mpmsrawfile',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='samplelist.Sample'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MHCurve',
        ),
        migrations.DeleteModel(
            name='MTCurve',
        ),
        migrations.AddField(
            model_name='mpmsdatatimeseries',
            name='raw_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplelist.MPMSRawFile'),
        ),
    ]
