# Generated by Django 2.1.7 on 2019-05-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplelist', '0008_auto_20190513_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpmsdatatimeseries',
            name='sequence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpmsrawfile',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpms_raw_files', to='samplelist.Sample'),
        ),
    ]
