# Generated by Django 2.1.7 on 2019-03-27 12:50

from django.db import migrations, models
import django.db.models.deletion
import mpms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('magnetic_field', models.FloatField(blank=True, null=True)),
                ('sequence', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('sample', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('comment', models.TextField()),
                ('raw_data', models.FileField(upload_to=mpms.models.mpms_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnetization', models.FloatField()),
                ('temperature', models.FloatField()),
                ('magnetic_field', models.FloatField()),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpms.Curve')),
            ],
        ),
        migrations.AddField(
            model_name='curve',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpms.DataFile'),
        ),
    ]
